"""Enforce ``sources.body NOT NULL`` (epic #470 / issue #481).

Revision ID: 0030_enforce_sources_body_not_null
Revises: 0029_create_slack_demand_digest
Create Date: 2026-06-07

Epic #470 (pre-userbase compat shim cleanup) sub-issue #481 promotes
:data:`opshub.projections.sources.sources_table` ``.body`` from
``nullable=True`` (Phase 10 step A2, ADR-0020 §(d) backward-compat) to
``nullable=False``. From this revision on **every** ``sources`` row is
guaranteed to carry a non-empty body.

Why this is safe pre-userbase
-----------------------------

ADR-0011 §設計判断のスタンス pins the project as pre-userbase: there is
no installed-base compatibility to preserve. The Phase 10 ``NULL`` shim
existed so the four Web-API connectors and the ``box_drive`` FS-scan
connector could land bodies opportunistically; the ``box_drive``
metadata-only path stamped ``body = NULL`` permanently. epic #470 lifts
that shim and pins the contract: stat-only / metadata-only connectors
satisfy the invariant by emitting ``body = summary`` (the existing
≤200-char preview is reused verbatim; ADR-0010 §不変条件).

The matching schema-level change rides on
:class:`opshub.domain.events.source.SourceObserved.body`, which the
follow-up commit on epic #470 promoted to ``str = Field(min_length=1)``
so every connector hits a Pydantic ``ValidationError`` rather than
silently writing ``NULL``.

Operator action (REQUIRED)
--------------------------

This migration drops every ``sources`` row whose ``body IS NULL`` (or
empty) and rebuilds the table because SQLite cannot ``ALTER COLUMN``
directly — promoting ``body`` to ``NOT NULL`` requires the standard
rebuild-via-temp-table dance. Historic ``NULL``-body rows would block
the rebuild's ``NOT NULL`` constraint, so the upgrade path explicitly
deletes them. They are regenerated by the next connector sync —
pre-userbase posture tolerates the round-trip.

Operators MUST follow up with:

* ``opshub projections rebuild`` — re-materialise non-source projections
  in case any dependent rows referenced the deleted sources.
* Per-connector cursor reset + full re-sync — see
  ``docs/upgrading.md`` §"Pre-userbase compat shim cleanup" for the
  per-connector commands. Every ``sources`` row must be rebuilt by the
  current mapper so the ``body = summary`` rule lands on stat-only /
  metadata-only paths.

The ``sources_fts`` virtual table + sync triggers are torn down before
the table swap (a FTS5 external-content vtable bound to a renamed table
would silently desync) and re-created with the current ``trigram``
tokenizer (Phase 15 / migration ``0028_rebuild_sources_fts_trigram``)
after the new ``sources`` table is in place + back-filled. Encrypted
databases (``[storage] encryption = true``, ADR-0021) migrate
transparently through SQLCipher.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0030_enforce_sources_body_not_null"
down_revision: str | Sequence[str] | None = "0029_create_slack_demand_digest"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# FTS tokenizer matches migration ``0028_rebuild_sources_fts_trigram`` —
# the rebuild here must end up with the same tokenizer the previous head
# left behind so an operator's ``opshub search`` queries stay continuous.
_TRIGRAM_TOKENIZE = "trigram"
_UNICODE61_TOKENIZE = "unicode61 remove_diacritics 2"


# Trigger DDL is copy-pasted from migration ``0019`` /
# ``0028_rebuild_sources_fts_trigram`` so this migration stays
# self-contained per the project-wide convention. The triggers form the
# write-path contract between ``sources`` writes and the FTS index;
# duplicating the SQL is the safer trade-off vs. importing across
# revisions.
_TRIGGER_AI = (
    "CREATE TRIGGER sources_fts_ai AFTER INSERT ON sources BEGIN "
    "INSERT INTO sources_fts(rowid, body) VALUES (new.rowid, new.body); "
    "END"
)
_TRIGGER_AD = (
    "CREATE TRIGGER sources_fts_ad AFTER DELETE ON sources BEGIN "
    "INSERT INTO sources_fts(sources_fts, rowid, body) "
    "VALUES ('delete', old.rowid, old.body); "
    "END"
)
_TRIGGER_AU = (
    "CREATE TRIGGER sources_fts_au AFTER UPDATE OF body ON sources BEGIN "
    "INSERT INTO sources_fts(sources_fts, rowid, body) "
    "VALUES ('delete', old.rowid, old.body); "
    "INSERT INTO sources_fts(rowid, body) VALUES (new.rowid, new.body); "
    "END"
)


def _drop_triggers() -> None:
    op.execute("DROP TRIGGER IF EXISTS sources_fts_au")
    op.execute("DROP TRIGGER IF EXISTS sources_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS sources_fts_ai")


def _create_triggers() -> None:
    op.execute(_TRIGGER_AI)
    op.execute(_TRIGGER_AD)
    op.execute(_TRIGGER_AU)


def _create_fts_table(tokenize: str) -> None:
    op.execute(
        "CREATE VIRTUAL TABLE sources_fts USING fts5("
        "body, "
        "content='sources', "
        "content_rowid='rowid', "
        f"tokenize='{tokenize}'"
        ")"
    )


def _backfill_fts() -> None:
    op.execute("INSERT INTO sources_fts(rowid, body) SELECT rowid, body FROM sources")


def _rebuild_sources(*, body_nullable: bool) -> None:
    """Rebuild the ``sources`` table with ``body``'s nullability flipped.

    Shared by :func:`upgrade` (NOT NULL) and :func:`downgrade` (NULL) so
    the temp-table dance lives in one place. The column shape mirrors
    :data:`opshub.projections.sources.sources_table` exactly — keep this
    in lock-step with that module's declaration.
    """
    body_constraint = "TEXT" if body_nullable else "TEXT NOT NULL"
    # Column types match what the original migrations declared via
    # SQLAlchemy on SQLite:
    #
    # * ``id`` — ``sa.String(length=26)`` → ``VARCHAR(26)``
    # * ``observed_at`` / ``updated_at`` — ``sa.DateTime(timezone=True)``
    #   → ``DATETIME`` (the SA-side ISO 8601 round-trip adapter binds
    #   on this exact name; raw ``TIMESTAMP`` skips the adapter and
    #   surfaces as ``str`` reads on the application side
    #   — ``TypeError: fromisoformat: argument must be str`` in tests
    #   pinned the drift).
    # * ``fingerprint`` — ``sa.Text()`` → ``TEXT`` (migration 0017 uses
    #   ``sa.Text()`` not ``sa.String``; the original test pin
    #   ``test_alembic_upgrade_adds_nullable_fingerprint_column`` asserts
    #   this).
    op.execute(
        f"""
        CREATE TABLE sources_new (
            id VARCHAR(26) NOT NULL PRIMARY KEY,
            connector_name TEXT NOT NULL,
            external_id TEXT NOT NULL,
            source_type TEXT NOT NULL,
            title TEXT NOT NULL,
            url TEXT,
            summary TEXT,
            observed_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            fingerprint TEXT,
            body {body_constraint},
            provenance_origin TEXT,
            provenance_trust TEXT,
            CONSTRAINT uq_sources_connector_name_external_id
                UNIQUE (connector_name, external_id)
        )
        """
    )
    op.execute(
        """
        INSERT INTO sources_new (
            id, connector_name, external_id, source_type, title, url, summary,
            observed_at, updated_at, fingerprint, body, provenance_origin,
            provenance_trust
        )
        SELECT
            id, connector_name, external_id, source_type, title, url, summary,
            observed_at, updated_at, fingerprint, body, provenance_origin,
            provenance_trust
        FROM sources
        """
    )
    op.execute("DROP TABLE sources")
    op.execute("ALTER TABLE sources_new RENAME TO sources")
    op.execute("CREATE INDEX ix_sources_connector_name ON sources (connector_name)")
    op.execute("CREATE INDEX ix_sources_updated_at ON sources (updated_at)")


def upgrade() -> None:
    """Drop NULL-body rows then rebuild ``sources`` with ``body NOT NULL``."""
    # 1. Tear down the FTS index + triggers. A FTS5 external-content
    #    vtable wired to ``sources`` would otherwise break when we
    #    drop / rename the underlying table.
    _drop_triggers()
    op.execute("DROP TABLE IF EXISTS sources_fts")

    # 2. Delete rows that would block the NOT NULL rebuild. Pre-userbase
    #    posture: the next connector sync regenerates them with the
    #    body = summary contract (ADR-0010 §不変条件).
    op.execute("DELETE FROM sources WHERE body IS NULL OR length(body) = 0")

    # 3. Rebuild the table with body NOT NULL.
    _rebuild_sources(body_nullable=False)

    # 4. Re-create the FTS index with the trigram tokenizer (matches the
    #    state migration 0028 left behind) and re-attach the triggers.
    _create_fts_table(_TRIGRAM_TOKENIZE)
    _backfill_fts()
    _create_triggers()


def downgrade() -> None:
    """Relax ``sources.body`` back to ``nullable=True`` (pre-#481 shape).

    Mirrors :func:`upgrade` in reverse. The deleted NULL-body rows are
    NOT restored — they were dropped from the projection but the event
    log keeps the historic events, so an ``opshub projections rebuild``
    would re-emit them. After this downgrade re-runs a connector sync,
    the projection still satisfies the relaxed (NULL-allowed) schema.
    """
    _drop_triggers()
    op.execute("DROP TABLE IF EXISTS sources_fts")
    _rebuild_sources(body_nullable=True)
    _create_fts_table(_TRIGRAM_TOKENIZE)
    _backfill_fts()
    _create_triggers()
